# Generated by Django 2.2 on 2020-02-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, max_length=300, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='posts.Group'),
        ),
    ]
